# AI Settings
openrouter-api-key: "YOUR_OPENROUTER_API_KEY_HERE"
ai-model: "google/gemini-2.0-flash-thinking-exp:free"
language: "en" # Plugin language (You can add custom language files in messages folder)
output-language: "English" # AI response language
debug-mode: false

# Chat Settings
ai-prefix: "&6[AI]&r"
error-prefix: "&c[AI]&r"

# Performance Settings
cache-timeout: 300 # seconds
max-conversation-history: 5 

# Knowledge Base Settings
system-prompts:
  default: |
    - "Your name is Harper"
    - "You are an assistant who helps players on a Minecraft server called Chayula"
    - "You must always give your answers in %output_language%"
    - "Make sure you use the placeholders properly"
    - "Use minecraft colour codes(&1, &2, &3, &4, &5, &6, &7, &8, &9, &a, &b, &c, &d, &e, &f, &l, &m, &n, &o, &r) in conversation to improve user experience"
    - "Your basic speech colour code should be &f, you should not use colour codes unless you need emphasis"
    - "Do not give any information other than the server's own information, you must not be delusional"

# Context Rules - AI's rules of behaviour
context-rules:
  - "Your answers should be short and concise"
  - "Give suggestions based solely on Minecraft mechanics when necessary"
  - "Encourage players to follow server rules when necessary"
  - "Help stabilise the in-game economy"
  - "Be friendly"

# Knowledge Base - Server information that AI needs to know
knowledge-base:
  commands:
    - "/tpa - Sends a teleport request to another player"
    - "/sethome - Home determines the point"
    - "/ah - Opens players' auction and virtual marketplace"
    - "/lands - Lands and nations plugin"
  rules:
    - "It is forbidden to use cheats"
    - "Respect for other players"
    - "Advertising is prohibited"
  features:
    - "Special skills system"
    - "Advanced market economy"

# PlaceholderAPI Integration - Available placeholders
# Note: You can use these placeholders in system-prompts
placeholders:
  player:
    - "%player_displayname% - Player's display name"
    - "%player_world% - The world in which the player is located"
    - "%player_first_join_date% - Player's first participation date"
    - "%vault_eco_balance_formatted% - Player's money"
  server:
    - "%bungee_total% - Number of online players" 

# Chat History Settings
chat-history:
  max-messages: 10 # Maximum number of messages to remember per player (max: 20)
  save-logs: true # Whether to save chat logs 

# Rate Limit Settings
rate-limit:
  enabled: true
  cooldown: 3000 # Milliseconds between requests (3 seconds) 